/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asu.girish.raman.crud.gradebook.graman1.netbeans.client.ui;

import asu.girish.raman.crud.gradebook.graman1.netbeans.client.AppealsClient;
import asu.girish.raman.crud.gradebook.graman1.netbeans.client.GradingItemsClient;
import asu.girish.raman.crud.gradebook.graman1.netbeans.client.StudentProfilesClient;
import com.sun.jersey.api.client.ClientResponse;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Girish
 */
public class StudentUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentUI
     */
    public StudentUI() {
        initComponents();
        customInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        VAGStudentID = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        VAGViewGrades = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        VAPGStudentID = new javax.swing.JComboBox<>();
        VAPGViewGrade = new javax.swing.JButton();
        VAPGGIID = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VGResponse = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FAStudentID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        FAGIID = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FAAppealMessage = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        FASubmitAppeal = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        FAResponse = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Select Student ID");

        VAGViewGrades.setText("View All Grades");
        VAGViewGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAGViewGradesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VAGStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(VAGViewGrades))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VAGStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VAGViewGrades)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("View All Grades", jPanel3);

        VAPGViewGrade.setText("View Grade");
        VAPGViewGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAPGViewGradeActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Student ID");

        jLabel2.setText("Select Grading Item");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(VAPGViewGrade)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(VAPGStudentID, 0, 150, Short.MAX_VALUE)
                        .addComponent(VAPGGIID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VAPGStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(VAPGGIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VAPGViewGrade)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("View A Particular Grade", jPanel4);

        VGResponse.setColumns(20);
        VGResponse.setRows(5);
        jScrollPane1.setViewportView(VGResponse);

        jLabel8.setText("Response");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Grades", jPanel1);

        jLabel4.setText("Select Student ID");

        jLabel5.setText("Select Grading Item");

        FAAppealMessage.setColumns(20);
        FAAppealMessage.setRows(5);
        jScrollPane3.setViewportView(FAAppealMessage);

        jLabel6.setText("Write a Message for Appeal");

        FASubmitAppeal.setText("Submit Appeal");
        FASubmitAppeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FASubmitAppealActionPerformed(evt);
            }
        });

        FAResponse.setColumns(20);
        FAResponse.setRows(5);
        jScrollPane4.setViewportView(FAResponse);

        jLabel7.setText("Response");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FASubmitAppeal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(FAStudentID, 0, 149, Short.MAX_VALUE)
                                .addComponent(FAGIID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FAStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FAGIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(FASubmitAppeal)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("File Appeal", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FASubmitAppealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FASubmitAppealActionPerformed
        int studentID = Integer.parseInt(FAStudentID.getSelectedItem().toString());
        int gradingItemID = Integer.parseInt(FAGIID.getSelectedItem().toString());
        String appealMessage = FAAppealMessage.getText();
        String requestMessage = "{\n"
                + "\t\"requestType\" : \"fileAnAppeal\",\n"
                + "\t\"studentId\" : " + studentID + ",\n"
                + "\t\"gradingItemId\" : " + gradingItemID + ",\n"
                + "\t\"appealMessage\" : \"" + appealMessage + "\"\n"
                + "}";
        ClientResponse response = appealsClient.fileAnAppeal(requestMessage);
        if (response.getStatus() != 204) {
            FAResponse.setText("Response Code: " + response.getStatus() + "\n" + response.getEntity(String.class));
        } else {
            FAResponse.setText("Response Code: " + response.getStatus() + "\nNo response body!");
        }
    }//GEN-LAST:event_FASubmitAppealActionPerformed

    private void VAGViewGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAGViewGradesActionPerformed
        int studentID = Integer.parseInt(VAGStudentID.getSelectedItem().toString());
        ClientResponse response = studentProfilesClient.getAllGradesForAStudent(studentID);
        if (response.getStatus() != 204) {
            VGResponse.setText("Response Code: " + response.getStatus() + "\n" + response.getEntity(String.class));
        } else {
            VGResponse.setText("Response Code: " + response.getStatus() + "\nNo response body!");
        }
    }//GEN-LAST:event_VAGViewGradesActionPerformed

    private void VAPGViewGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAPGViewGradeActionPerformed
        int studentID = Integer.parseInt(VAPGStudentID.getSelectedItem().toString());
        int gradingItemID = Integer.parseInt(VAPGGIID.getSelectedItem().toString());
        ClientResponse response = studentProfilesClient.getGradeForAStudent(studentID, gradingItemID);
        if (response.getStatus() != 204) {
            VGResponse.setText("Response Code: " + response.getStatus() + "\n" + response.getEntity(String.class));
        } else {
            VGResponse.setText("Response Code: " + response.getStatus() + "\nNo response body!");
        }
    }//GEN-LAST:event_VAPGViewGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FAAppealMessage;
    private javax.swing.JComboBox<String> FAGIID;
    private javax.swing.JTextArea FAResponse;
    private javax.swing.JComboBox<String> FAStudentID;
    private javax.swing.JButton FASubmitAppeal;
    private javax.swing.JComboBox<String> VAGStudentID;
    private javax.swing.JButton VAGViewGrades;
    private javax.swing.JComboBox<String> VAPGGIID;
    private javax.swing.JComboBox<String> VAPGStudentID;
    private javax.swing.JButton VAPGViewGrade;
    private javax.swing.JTextArea VGResponse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
    StudentProfilesClient studentProfilesClient;
    GradingItemsClient gradingItemsClient;
    AppealsClient appealsClient;

    private void customInitComponents() {
        studentProfilesClient = new StudentProfilesClient();
        appealsClient = new AppealsClient();
        gradingItemsClient = new GradingItemsClient();
        setStudentIDs();
        setGradingItemIDs();
    }

    private void setStudentIDs() {
        String studentIDs = studentProfilesClient.getAllStudentIDs();
        Integer[] allStudentIDs = convertStringToArray(studentIDs);
        FAStudentID.setModel(new DefaultComboBoxModel((Object[]) allStudentIDs));
        VAGStudentID.setModel(new DefaultComboBoxModel((Object[]) allStudentIDs));
        VAPGStudentID.setModel(new DefaultComboBoxModel((Object[]) allStudentIDs));
    }

    private void setGradingItemIDs() {
        String gradingItemIDs = gradingItemsClient.getAllGradingItemIDs();
        Integer[] allGradingItemIDs = convertStringToArray(gradingItemIDs);
        VAPGGIID.setModel(new DefaultComboBoxModel((Object[]) allGradingItemIDs));
        FAGIID.setModel(new DefaultComboBoxModel((Object[]) allGradingItemIDs));
    }

    private Integer[] convertStringToArray(String input) {
        input = input.substring(1, input.length() - 1);
        if (input.equals("")) {
            return new Integer[]{};
        } else if (!input.contains(",")) {
            return new Integer[]{Integer.parseInt(input)};
        } else {
            String[] parts = input.split(",");
            List<Integer> list = new ArrayList<>();
            for (String s : parts) {
                list.add(Integer.parseInt(s.trim()));
            }
            Object[] objectArray = list.toArray();
            Integer[] integerArray = Arrays.copyOf(objectArray, objectArray.length, Integer[].class);
            return integerArray;
        }
    }
}
